### ISSUE TITLE
allpaths & somepath returning no results

### ISSUE THREAD

**Issue by Ratchette** [googleinterns/dagger-query#61]
## Expected Behavior
Using the example data, the following queries should return 1 or more results
* allpaths com.google.daggerquery.example.models.Tourist com.google.daggerquery.example.models.Hotel
* allpaths com.google.daggerquery.example.models.Tourist com.google.daggerquery.example.models.InflatableDonut
* somepath com.google.daggerquery.example.models.Tourist com.google.daggerquery.example.models.InflatableDonut

## Actual Behavior
![image](https://user-images.githubusercontent.com/3325484/93997911-cd9b2600-fd8b-11ea-8176-1873f6ee0356.png)

## Steps to Reproduce the Problem

1. Launch the UI using `bash dagger-query-ui-example.sh`
1. Enter one of the above queries

**Comment by margaritiko** [comment]
Thanks for this issue!

With the [latest changes](https://github.com/googleinterns/dagger-query/pull/42) in the example target `com.google.daggerquery.example.models.Tourist` not connected with either `com.google.daggerquery.example.models.InflatableDonut` nor with `com.google.daggerquery.example.models.Hotel` since the graph is directed. I think these questions were relevant before these changes.

In [this PR](https://github.com/googleinterns/dagger-query/pull/64) I have placed queries which can be used as an example.

**Comment by Ratchette** [comment]
Thanks for looking into it!

I'm glad to hear that this was just user error :)
